# Generated by Django 5.2.5 on 2025-12-01 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Plataforma del pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Link de seguimiento')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción de lo solicitado')),
                ('imagen_ref1', models.ImageField(blank=True, null=True, upload_to='pedidos/')),
                ('imagen_ref2', models.ImageField(blank=True, null=True, upload_to='pedidos/')),
                ('imagen_ref3', models.ImageField(blank=True, null=True, upload_to='pedidos/')),
                ('fecha_necesita', models.DateField(blank=True, null=True, verbose_name='Fecha en que necesita el producto')),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Completado', 'COMPLETADO'), ('Parcial', 'PARCIAL')], default='Pendiente', max_length=20)),
                ('plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.plataforma')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.producto')),
            ],
        ),
    ]
