# Generated by Django 5.2.5 on 2025-11-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='talla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
