# Generated by Django 5.2.5 on 2025-12-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_pedido_producto_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='nombre',
            field=models.CharField(choices=[('Instagram', 'INSTAGRAM'), ('Facebook', 'FACEBOOK'), ('TikTok', 'TIKTOK'), ('WhatsApp', 'WHATSAPP')], max_length=50, unique=True, verbose_name='Plataforma de origen del pedido'),
        ),
    ]
